version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - default
    links:
      - db
    depends_on: 
      - db
    environment: 
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 60
  db:
    image: mysql:8.0.16
    command: ['--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stundenplan2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8087:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    links:
      - db
    ports:
      - "8086:80"
    environment: 
      MYSQL_USER: user
      MYSQL_PASSWORD: mysqlpw
      MYSQL_ROOT_PASSWORD: root
volumes:
  persistent: